### PR TITLE
export all globals listed in documentation

### PR DESCRIPTION
**Pull request by MAKIO135**
cf #2

### CODE REVIEW

**Comment by aweary** [comment]
@MAKIO135  What is the `?module` suffix for?

**Review by aweary — CHANGES_REQUESTED** [review]
I found the explanation on https://unpkg.com/. @MAKIO135 it seems like the `?module` part is handled by unpkg, not something we use in the source code. Can you remove those from the exports? After that I'm good with merging.

**Comment by MAKIO135** [comment]
Arf, this is my error 🤦‍♂️
I need this in Observable to import them as ES6 modules.

**Comment by MAKIO135** [comment]
removed them, sorry

**Review by aweary — APPROVED** [review]
Thanks!

**Comment by MAKIO135** [comment]
Wow, thanks ! 🤩

**Comment by MAKIO135** [comment]
you may need to bump minor version and republish package on NPM, but that's awesome ! Thanks again for this work 🙏

**Comment by aweary** [comment]
@MAKIO135 published `0.5.0`

**Comment by MAKIO135** [comment]
Thanks !

**Pull request merged**
